# Generated by Django 5.0.2 on 2024-02-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('room_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'room_name')},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('attchment_url', models.URLField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatroom')),
            ],
        ),
    ]
