# Generated by Django 5.0.2 on 2024-02-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatroom_alter_classroom_unique_together_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='attchment_url',
            new_name='attachment_url',
        ),
    ]
