# Generated by Django 5.0.2 on 2024-02-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(blank=True),
        ),
    ]
