# Generated by Django 5.0.2 on 2024-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_message_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(null=True),
        ),
    ]
